<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bosak.XPath.Api\Bosak.XPath.Api.csproj" />
    <ProjectReference Include="..\..\src\Bosak.XPath.Core\Bosak.XPath.Core.csproj" />
    <ProjectReference Include="..\..\src\Bosak.XPath.Runtime\Bosak.XPath.Runtime.csproj" />
    <ProjectReference Include="..\..\src\Bosak.XPath.Standard\Bosak.XPath.Standard.csproj" />
    <ProjectReference Include="..\..\src\Bosak.XPath.Providers\Bosak.XPath.Providers.csproj" />
  </ItemGroup>

</Project>
