<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bosak.XPath.Core\Bosak.XPath.Core.csproj" />
    <ProjectReference Include="..\Bosak.XPath.Providers\Bosak.XPath.Providers.csproj" />
    <ProjectReference Include="..\Bosak.XPath.Runtime\Bosak.XPath.Runtime.csproj" />
  </ItemGroup>

</Project>
