<Project>

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Version>1.0.0</Version>
    <Authors>Fytala</Authors>
    <Company>Fytala</Company>
    <Copyright>Copyright (c) 2026 FYTALA</Copyright>
    <PackageLicenseFile>license.md</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)..\license.md" Pack="true" PackagePath="\" />
    <None Include="$(MSBuildThisFileDirectory)..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
